//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices_AlibabaShop.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SupplierFeedback
    {
        public System.Guid Id { get; set; }
        public System.Guid Product_Id { get; set; }
        public System.Guid WholeSaler_Id { get; set; }
        public string WholeSaler { get; set; }
        public string Product { get; set; }
        public string Feedback { get; set; }
        public System.DateTime PostTime { get; set; }
        public byte Status { get; set; }
    }
}
