//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices_AlibabaShop.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SupplierBasicInfo
    {
        public System.Guid Id { get; set; }
        public string Supplier_Name { get; set; }
        public string Ownership { get; set; }
        public decimal Revenue { get; set; }
        public string Logo { get; set; }
    }
}
