//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices_AlibabaShop.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Transaction
    {
        public System.Guid Order_Id { get; set; }
        public System.Guid Product_Id { get; set; }
        public System.Guid Suplier_Id { get; set; }
        public System.Guid WholeSaler_Id { get; set; }
        public string Product_Name { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalPaid { get; set; }
        public byte Status { get; set; }
    }
}
