//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServices_AlibabaShop.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Wholesaler
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Ownership { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Email { get; set; }
        public byte Status { get; set; }
    }
}
