//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_Category", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class vw_Category : object
    {
        
        private System.Guid IdField;
        
        private string Main_CategoryField;
        
        private string NameField;
        
        private System.Nullable<System.Guid> PIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Main_Category
        {
            get
            {
                return this.Main_CategoryField;
            }
            set
            {
                this.Main_CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PId
        {
            get
            {
                return this.PIdField;
            }
            set
            {
                this.PIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlibabaShopFaultedException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.exception")]
    public partial class AlibabaShopFaultedException : object
    {
        
        private string errorCodeField;
        
        private string messageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class Category : object
    {
        
        private CommonReference.Category[] Category1Field;
        
        private CommonReference.Category Category2Field;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private System.Nullable<System.Guid> PIdField;
        
        private CommonReference.Product[] ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Category[] Category1
        {
            get
            {
                return this.Category1Field;
            }
            set
            {
                this.Category1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Category Category2
        {
            get
            {
                return this.Category2Field;
            }
            set
            {
                this.Category2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> PId
        {
            get
            {
                return this.PIdField;
            }
            set
            {
                this.PIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Product[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class Product : object
    {
        
        private CommonReference.Category CategoryField;
        
        private System.Guid Category_IdField;
        
        private string DescriptionField;
        
        private System.Nullable<int> DiscountField;
        
        private System.Guid IdField;
        
        private string ImageField;
        
        private int MaximumOrderField;
        
        private int MinimumOrderField;
        
        private string NameField;
        
        private System.DateTime PostDateField;
        
        private decimal PriceField;
        
        private CommonReference.ProductFeedback[] ProductFeedbacksField;
        
        private CommonReference.PurchaseOrder[] PurchaseOrdersField;
        
        private int QtyInHandField;
        
        private CommonReference.Quotation[] QuotationsField;
        
        private byte StatusField;
        
        private CommonReference.Supplier SupplierField;
        
        private System.Guid Supplier_IdField;
        
        private int ViewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Category Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Category_Id
        {
            get
            {
                return this.Category_IdField;
            }
            set
            {
                this.Category_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaximumOrder
        {
            get
            {
                return this.MaximumOrderField;
            }
            set
            {
                this.MaximumOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinimumOrder
        {
            get
            {
                return this.MinimumOrderField;
            }
            set
            {
                this.MinimumOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PostDate
        {
            get
            {
                return this.PostDateField;
            }
            set
            {
                this.PostDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.ProductFeedback[] ProductFeedbacks
        {
            get
            {
                return this.ProductFeedbacksField;
            }
            set
            {
                this.ProductFeedbacksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.PurchaseOrder[] PurchaseOrders
        {
            get
            {
                return this.PurchaseOrdersField;
            }
            set
            {
                this.PurchaseOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtyInHand
        {
            get
            {
                return this.QtyInHandField;
            }
            set
            {
                this.QtyInHandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Quotation[] Quotations
        {
            get
            {
                return this.QuotationsField;
            }
            set
            {
                this.QuotationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Supplier Supplier
        {
            get
            {
                return this.SupplierField;
            }
            set
            {
                this.SupplierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Supplier_Id
        {
            get
            {
                return this.Supplier_IdField;
            }
            set
            {
                this.Supplier_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Views
        {
            get
            {
                return this.ViewsField;
            }
            set
            {
                this.ViewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class Supplier : object
    {
        
        private string AddressField;
        
        private CommonReference.Country CountryField;
        
        private System.Guid Country_IdField;
        
        private string DescriptionField;
        
        private string EmailField;
        
        private int EmployeesField;
        
        private int EstablishedYearField;
        
        private System.Guid IdField;
        
        private string LogoField;
        
        private string NameField;
        
        private CommonReference.Ownership OwnershipField;
        
        private System.Guid Ownership_IdField;
        
        private CommonReference.Product[] ProductsField;
        
        private CommonReference.PurchaseOrder[] PurchaseOrdersField;
        
        private CommonReference.Quotation[] QuotationsField;
        
        private System.DateTime RegisterDateField;
        
        private decimal RevenueField;
        
        private byte StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Country Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Country_Id
        {
            get
            {
                return this.Country_IdField;
            }
            set
            {
                this.Country_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstablishedYear
        {
            get
            {
                return this.EstablishedYearField;
            }
            set
            {
                this.EstablishedYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo
        {
            get
            {
                return this.LogoField;
            }
            set
            {
                this.LogoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Ownership Ownership
        {
            get
            {
                return this.OwnershipField;
            }
            set
            {
                this.OwnershipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Ownership_Id
        {
            get
            {
                return this.Ownership_IdField;
            }
            set
            {
                this.Ownership_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Product[] Products
        {
            get
            {
                return this.ProductsField;
            }
            set
            {
                this.ProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.PurchaseOrder[] PurchaseOrders
        {
            get
            {
                return this.PurchaseOrdersField;
            }
            set
            {
                this.PurchaseOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Quotation[] Quotations
        {
            get
            {
                return this.QuotationsField;
            }
            set
            {
                this.QuotationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisterDate
        {
            get
            {
                return this.RegisterDateField;
            }
            set
            {
                this.RegisterDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Revenue
        {
            get
            {
                return this.RevenueField;
            }
            set
            {
                this.RevenueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductFeedback", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class ProductFeedback : object
    {
        
        private string FeedbackField;
        
        private System.Guid IdField;
        
        private System.DateTime PostTimeField;
        
        private CommonReference.Product ProductField;
        
        private System.Guid Product_IdField;
        
        private byte StatusField;
        
        private CommonReference.WholeSaler WholeSalerField;
        
        private System.Guid WholeSaler_IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Feedback
        {
            get
            {
                return this.FeedbackField;
            }
            set
            {
                this.FeedbackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PostTime
        {
            get
            {
                return this.PostTimeField;
            }
            set
            {
                this.PostTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Product_Id
        {
            get
            {
                return this.Product_IdField;
            }
            set
            {
                this.Product_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.WholeSaler WholeSaler
        {
            get
            {
                return this.WholeSalerField;
            }
            set
            {
                this.WholeSalerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WholeSaler_Id
        {
            get
            {
                return this.WholeSaler_IdField;
            }
            set
            {
                this.WholeSaler_IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseOrder", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class PurchaseOrder : object
    {
        
        private System.DateTime ArrivedDateField;
        
        private System.Guid IdField;
        
        private System.DateTime OrderDateField;
        
        private string OrderNoField;
        
        private CommonReference.Product ProductField;
        
        private System.Guid Product_IdField;
        
        private int QtyField;
        
        private CommonReference.ShipMethod ShipMethodField;
        
        private System.Guid ShipMethod_IdField;
        
        private byte StatusField;
        
        private System.Guid Suplier_IdField;
        
        private CommonReference.Supplier SupplierField;
        
        private decimal TotalPaidField;
        
        private CommonReference.UnitMeasure UnitMeasureField;
        
        private System.Guid UnitMeasure_IdField;
        
        private CommonReference.WholeSaler WholeSalerField;
        
        private System.Guid WholeSaler_IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivedDate
        {
            get
            {
                return this.ArrivedDateField;
            }
            set
            {
                this.ArrivedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo
        {
            get
            {
                return this.OrderNoField;
            }
            set
            {
                this.OrderNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Product_Id
        {
            get
            {
                return this.Product_IdField;
            }
            set
            {
                this.Product_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.ShipMethod ShipMethod
        {
            get
            {
                return this.ShipMethodField;
            }
            set
            {
                this.ShipMethodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ShipMethod_Id
        {
            get
            {
                return this.ShipMethod_IdField;
            }
            set
            {
                this.ShipMethod_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Suplier_Id
        {
            get
            {
                return this.Suplier_IdField;
            }
            set
            {
                this.Suplier_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Supplier Supplier
        {
            get
            {
                return this.SupplierField;
            }
            set
            {
                this.SupplierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPaid
        {
            get
            {
                return this.TotalPaidField;
            }
            set
            {
                this.TotalPaidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.UnitMeasure UnitMeasure
        {
            get
            {
                return this.UnitMeasureField;
            }
            set
            {
                this.UnitMeasureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UnitMeasure_Id
        {
            get
            {
                return this.UnitMeasure_IdField;
            }
            set
            {
                this.UnitMeasure_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.WholeSaler WholeSaler
        {
            get
            {
                return this.WholeSalerField;
            }
            set
            {
                this.WholeSalerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WholeSaler_Id
        {
            get
            {
                return this.WholeSaler_IdField;
            }
            set
            {
                this.WholeSaler_IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class Quotation : object
    {
        
        private string FileAttachmentField;
        
        private System.Guid IdField;
        
        private string MessageField;
        
        private CommonReference.Product ProductField;
        
        private System.Guid Product_IdField;
        
        private int QtyField;
        
        private System.DateTime RequestDateField;
        
        private byte StatusField;
        
        private System.Nullable<decimal> SubTotalField;
        
        private CommonReference.Supplier SupplierField;
        
        private System.Guid Supplier_IdField;
        
        private System.Nullable<decimal> TaxAmountField;
        
        private System.Nullable<decimal> TotalField;
        
        private CommonReference.UnitMeasure UnitMeasureField;
        
        private System.Guid UnitMeasure_IdField;
        
        private System.Nullable<decimal> UnitPriceField;
        
        private CommonReference.WholeSaler WholeSalerField;
        
        private System.Guid WholeSaler_IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileAttachment
        {
            get
            {
                return this.FileAttachmentField;
            }
            set
            {
                this.FileAttachmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Product Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Product_Id
        {
            get
            {
                return this.Product_IdField;
            }
            set
            {
                this.Product_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty
        {
            get
            {
                return this.QtyField;
            }
            set
            {
                this.QtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate
        {
            get
            {
                return this.RequestDateField;
            }
            set
            {
                this.RequestDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubTotal
        {
            get
            {
                return this.SubTotalField;
            }
            set
            {
                this.SubTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Supplier Supplier
        {
            get
            {
                return this.SupplierField;
            }
            set
            {
                this.SupplierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Supplier_Id
        {
            get
            {
                return this.Supplier_IdField;
            }
            set
            {
                this.Supplier_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TaxAmount
        {
            get
            {
                return this.TaxAmountField;
            }
            set
            {
                this.TaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.UnitMeasure UnitMeasure
        {
            get
            {
                return this.UnitMeasureField;
            }
            set
            {
                this.UnitMeasureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UnitMeasure_Id
        {
            get
            {
                return this.UnitMeasure_IdField;
            }
            set
            {
                this.UnitMeasure_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitPrice
        {
            get
            {
                return this.UnitPriceField;
            }
            set
            {
                this.UnitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.WholeSaler WholeSaler
        {
            get
            {
                return this.WholeSalerField;
            }
            set
            {
                this.WholeSalerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WholeSaler_Id
        {
            get
            {
                return this.WholeSaler_IdField;
            }
            set
            {
                this.WholeSaler_IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WholeSaler", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class WholeSaler : object
    {
        
        private string AddressField;
        
        private CommonReference.Country CountryField;
        
        private System.Guid Country_IdField;
        
        private string DescriptionField;
        
        private string EmailField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private System.Guid Ownership_IdField;
        
        private CommonReference.ProductFeedback[] ProductFeedbacksField;
        
        private CommonReference.PurchaseOrder[] PurchaseOrdersField;
        
        private CommonReference.Quotation[] QuotationsField;
        
        private System.DateTime RegisterDateField;
        
        private byte StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Country Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Country_Id
        {
            get
            {
                return this.Country_IdField;
            }
            set
            {
                this.Country_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Ownership_Id
        {
            get
            {
                return this.Ownership_IdField;
            }
            set
            {
                this.Ownership_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.ProductFeedback[] ProductFeedbacks
        {
            get
            {
                return this.ProductFeedbacksField;
            }
            set
            {
                this.ProductFeedbacksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.PurchaseOrder[] PurchaseOrders
        {
            get
            {
                return this.PurchaseOrdersField;
            }
            set
            {
                this.PurchaseOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Quotation[] Quotations
        {
            get
            {
                return this.QuotationsField;
            }
            set
            {
                this.QuotationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisterDate
        {
            get
            {
                return this.RegisterDateField;
            }
            set
            {
                this.RegisterDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class Country : object
    {
        
        private CommonReference.Harbor[] HarborsField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private string RegionCodeField;
        
        private CommonReference.Supplier[] SuppliersField;
        
        private CommonReference.WholeSaler[] WholeSalersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Harbor[] Harbors
        {
            get
            {
                return this.HarborsField;
            }
            set
            {
                this.HarborsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionCode
        {
            get
            {
                return this.RegionCodeField;
            }
            set
            {
                this.RegionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Supplier[] Suppliers
        {
            get
            {
                return this.SuppliersField;
            }
            set
            {
                this.SuppliersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.WholeSaler[] WholeSalers
        {
            get
            {
                return this.WholeSalersField;
            }
            set
            {
                this.WholeSalersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Harbor", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class Harbor : object
    {
        
        private CommonReference.Country CountryField;
        
        private System.Guid Country_IdField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        private byte StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Country Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Country_Id
        {
            get
            {
                return this.Country_IdField;
            }
            set
            {
                this.Country_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ownership", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class Ownership : object
    {
        
        private System.Guid IdField;
        
        private string NameField;
        
        private CommonReference.Supplier[] SuppliersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Supplier[] Suppliers
        {
            get
            {
                return this.SuppliersField;
            }
            set
            {
                this.SuppliersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipMethod", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class ShipMethod : object
    {
        
        private System.Guid IdField;
        
        private string NameField;
        
        private CommonReference.PurchaseOrder[] PurchaseOrdersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.PurchaseOrder[] PurchaseOrders
        {
            get
            {
                return this.PurchaseOrdersField;
            }
            set
            {
                this.PurchaseOrdersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnitMeasure", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.dal")]
    public partial class UnitMeasure : object
    {
        
        private System.Guid IdField;
        
        private string NameField;
        
        private CommonReference.PurchaseOrder[] PurchaseOrdersField;
        
        private CommonReference.Quotation[] QuotationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.PurchaseOrder[] PurchaseOrders
        {
            get
            {
                return this.PurchaseOrdersField;
            }
            set
            {
                this.PurchaseOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommonReference.Quotation[] Quotations
        {
            get
            {
                return this.QuotationsField;
            }
            set
            {
                this.QuotationsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonReference.ICommonServices")]
    public interface ICommonServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonServices/getVwCategory", ReplyAction="http://tempuri.org/ICommonServices/getVwCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CommonReference.AlibabaShopFaultedException), Action="http://tempuri.org/ICommonServices/getVwCategoryAlibabaShopFaultedExceptionFault", Name="AlibabaShopFaultedException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.exception")]
        System.Threading.Tasks.Task<CommonReference.vw_Category[]> getVwCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonServices/viewCategory", ReplyAction="http://tempuri.org/ICommonServices/viewCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CommonReference.AlibabaShopFaultedException), Action="http://tempuri.org/ICommonServices/viewCategoryAlibabaShopFaultedExceptionFault", Name="AlibabaShopFaultedException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.exception")]
        System.Threading.Tasks.Task<CommonReference.Category[]> viewCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonServices/viewTopSupplier", ReplyAction="http://tempuri.org/ICommonServices/viewTopSupplierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CommonReference.AlibabaShopFaultedException), Action="http://tempuri.org/ICommonServices/viewTopSupplierAlibabaShopFaultedExceptionFaul" +
            "t", Name="AlibabaShopFaultedException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.exception")]
        System.Threading.Tasks.Task<CommonReference.Supplier[]> viewTopSupplierAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonServices/viewTopProduct", ReplyAction="http://tempuri.org/ICommonServices/viewTopProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CommonReference.AlibabaShopFaultedException), Action="http://tempuri.org/ICommonServices/viewTopProductAlibabaShopFaultedExceptionFault" +
            "", Name="AlibabaShopFaultedException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.exception")]
        System.Threading.Tasks.Task<CommonReference.Product[]> viewTopProductAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonServices/searchProduct", ReplyAction="http://tempuri.org/ICommonServices/searchProductResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CommonReference.AlibabaShopFaultedException), Action="http://tempuri.org/ICommonServices/searchProductAlibabaShopFaultedExceptionFault", Name="AlibabaShopFaultedException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.exception")]
        System.Threading.Tasks.Task<CommonReference.Product> searchProductAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonServices/searchSupplier", ReplyAction="http://tempuri.org/ICommonServices/searchSupplierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CommonReference.AlibabaShopFaultedException), Action="http://tempuri.org/ICommonServices/searchSupplierAlibabaShopFaultedExceptionFault" +
            "", Name="AlibabaShopFaultedException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices_AlibabaShop.exception")]
        System.Threading.Tasks.Task<CommonReference.Supplier> searchSupplierAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public interface ICommonServicesChannel : CommonReference.ICommonServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public partial class CommonServicesClient : System.ServiceModel.ClientBase<CommonReference.ICommonServices>, CommonReference.ICommonServices
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CommonServicesClient() : 
                base(CommonServicesClient.GetDefaultBinding(), CommonServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.bs.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(CommonServicesClient.GetBindingForEndpoint(endpointConfiguration), CommonServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CommonServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CommonServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CommonReference.vw_Category[]> getVwCategoryAsync()
        {
            return base.Channel.getVwCategoryAsync();
        }
        
        public System.Threading.Tasks.Task<CommonReference.Category[]> viewCategoryAsync()
        {
            return base.Channel.viewCategoryAsync();
        }
        
        public System.Threading.Tasks.Task<CommonReference.Supplier[]> viewTopSupplierAsync()
        {
            return base.Channel.viewTopSupplierAsync();
        }
        
        public System.Threading.Tasks.Task<CommonReference.Product[]> viewTopProductAsync()
        {
            return base.Channel.viewTopProductAsync();
        }
        
        public System.Threading.Tasks.Task<CommonReference.Product> searchProductAsync(string name)
        {
            return base.Channel.searchProductAsync(name);
        }
        
        public System.Threading.Tasks.Task<CommonReference.Supplier> searchSupplierAsync(string name)
        {
            return base.Channel.searchSupplierAsync(name);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.bs))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.bs))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/Design_Time_Addresses/WcfServices_AlibabaShop.common/CommonServi" +
                        "ces/bs");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CommonServicesClient.GetBindingForEndpoint(EndpointConfiguration.bs);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CommonServicesClient.GetEndpointAddress(EndpointConfiguration.bs);
        }
        
        public enum EndpointConfiguration
        {
            
            bs,
        }
    }
}
